#!/bin/sh
while [ 1 == 1 ]; do
	echo d
	ls -lr d >/dev/null
	sleep 1
	echo d2
	ls -lr d2 >/dev/null
	sleep 1
	echo d3
	ls -lr d3 >/dev/null
	sleep 1
	echo d4
	ls -lr d4 >/dev/null
	sleep 1
	ls -lr d5 >/dev/null
	sleep 1
	ls -lr d6 >/dev/null
	sleep 1
done

