.\" Access Control Lists manual pages
.\"
.\" (C) 2002 Andreas Gruenbacher, <a.gruenbacher@computer.org>
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.TH ACL_CHECK 3 "Linux ACL Library" "March 2002" "Access Control Lists"
.SH NAME
acl_error \- convert an ACL error code to a text message
.SH LIBRARY
Linux Access Control Lists library (libacl, \-lacl).
.SH C SYNOPSIS
.sp
.nf
.B #include <sys/types.h>
.B #include <sys/acl.h>
.sp
.B "const char * acl_error (int \f2code\f3);"
.Op
.SH DESCRIPTION
The
.B acl_error
function converts an ACL error code such as returned by the
.BR acl_check (3)
function to a text message describing the error condition. In the
\(lqPOSIX\(rq locale,
.B acl_check
returns the following descriptions for the error codes:
.IP
ACL_MULTI_ERROR (\(lqMultiple entries\(rq)
.IP
ACL_DUPLICATE_ERROR (\(lqDuplicate entries\(rq)
.IP
ACL_MISS_ERROR (\(lqMissing or wrong entry\(rq)
.IP
ACL_ENTRY_ERROR (\(lqInvalid entry type\(rq)
.SH RETURN VALUE
The
.B acl_error
function returns a text message if the error code is recognized, and a value of
NULL otherwise.
.SH STANDARDS
This is a non-portable, Linux specific extension to the ACL manipulation
functions defined in IEEE Std 1003.1e draft 17 (\(lqPOSIX.1e\(rq, abandoned).
.SH AUTHOR
Written by
.I "Andreas Gruenbacher"
<a.gruenbacher@computer.org>.
.SH SEE ALSO
.BR acl_valid (3),
.BR acl (5)
