.\" Access Control Lists manual pages
.\"
.\" (C) 2002 Andreas Gruenbacher, <a.gruenbacher@computer.org>
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.TH ACL_CHECK 3 "Linux ACL Library" "March 2002" "Access Control Lists"
.SH NAME
acl_check \- check an ACL for validity
.SH LIBRARY
Linux Access Control Lists library (libacl, \-lacl).
.SH C SYNOPSIS
.sp
.nf
.B #include <sys/types.h>
.B #include <sys/acl.h>
.sp
.B "int acl_check (acl_t \f2acl\f3, int *\f2last\f3);"
.Op
.SH DESCRIPTION
The
.B acl_check
function checks the ACL referred to by the argument
.I acl
for validity.
.PP
The three required entries ACL_USER_OBJ, ACL_GROUP_OBJ, and ACL_OTHER
must exist exactly once in the ACL. If the ACL contains any ACL_USER or
ACL_GROUP entries, then an ACL_MASK entry is also required. The ACL
may contain at most one ACL_MASK entry.
.PP
The user identifiers must be unique among all entries of type ACL_USER.
The group identifiers must be unique among all entries of type ACL_GROUP.
.PP
If the ACL referred to by
.I acl
is invalid,
.B acl_check
returns a positive error code that indicates which type of error was detected.
The following symbolic error codes are defined:
.TP
.B ACL_MULTI_ERROR
The ACL contains multiple entries that have a tag type
that may occur at most once.
.TP
.B ACL_DUPLICATE_ERROR
The ACL contains multiple ACL_USER entries with the same user ID, or
multiple ACL_GROUP entries with the same group ID.
.TP
.B ACL_MISS_ERROR
A required entry is missing.
.TP
.B ACL_ENTRY_ERROR
The ACL contains an invalid entry tag type.
.PP
The
.BR acl_error (3)
function can be used to translate error codes to text messages.
.PP
In addition, if the pointer
.I last
is not NULL,
.B acl_check
assigns the number of the ACL entry at which the error was detected to
the value pointed to by
.IR last .
Entries are numbered starting with 0, in the order in which they would be
returned by the
.BR acl_get_entry (3)
function.
.SH RETURN VALUE
If successful, the
.B acl_check
function returns 0 if the ACL referred to by
.I acl
is valid, and a positive error code if the ACL is invalid.
Otherwise, a value of -1 is returned and the global variable
.B errno
is set to indicate the error.
.SH ERRORS
If any of the following conditions occur, the
.B acl_check
function returns -1 and sets
.B errno
to the corresponding value:
.TP
.SM
\%[EINVAL]
The argument
.I acl
is not a valid pointer to an ACL.
.SH STANDARDS
This is a non-portable, Linux specific extension to the ACL manipulation
functions defined in IEEE Std 1003.1e draft 17 (\(lqPOSIX.1e\(rq, abandoned).
.SH AUTHOR
Written by
.I "Andreas Gruenbacher"
<a.gruenbacher@computer.org>.
.SH SEE ALSO
.BR acl_valid (3),
.BR acl (5)
