.\" Access Control Lists manual pages
.\"
.\" (C) 2002 Andreas Gruenbacher, <a.gruenbacher@computer.org>
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.TH ACL_GET_TAG_TYPE 3 "Linux ACL Library" "March 2002" "Access Control Lists"
.SH NAME
acl_get_tag_type \- get the tag type of an ACL entry
.SH LIBRARY
Linux Access Control Lists library (libacl, \-lacl).
.SH C SYNOPSIS
.sp
.nf
.B #include <sys/types.h>
.B #include <sys/acl.h>
.sp
.B "int acl_get_tag_type (acl_entry_t \f2entry_d\f3, "
.B "                      acl_tag_t *\f2tag_type_p\f3);"
.Op
.SH DESCRIPTION
The
.B acl_get_tag_type
function assigns to the value pointed to by
.I tag_type_p
the tag type for the ACL entry indicated by the argument
.IR entry_d .
.PP
The argument
.I entry_d
and any other ACL entry descriptors that refer to entries in the same
ACL continue to refer to those entries. The order of all existing
entries in the ACL remain unchanged.
.SH RETURN VALUE
The value 0 is returned if successful; otherwise the value -1 is
returned and the global variable errno is set to indicate the error.
.SH ERRORS
If any of the following conditions occur, the
.B acl_get_tag_type
function returns -1 and sets
.B errno
to the corresponding value:
.TP
.SM
\%[EINVAL]
The argument
.I entry_d
is not a valid descriptor for an ACL entry.
.SH STANDARDS
IEEE Std 1003.1e draft 17 (\(lqPOSIX.1e\(rq, abandoned)
.SH AUTHOR
Derived from the FreeBSD manual pages written by
.IR "Robert N M Watson" ;
and adapted for Linux by
.I "Andreas Gruenbacher"
<a.gruenbacher@computer.org>.
.SH SEE ALSO
.BR acl_create_entry (3),
.BR acl_get_entry (3),
.BR acl_get_qualifier (3),
.BR acl_set_qualifier (3),
.BR acl_set_tag_type (3),
.BR acl_get_permset (3),
.BR acl_set_pe)mset (3),
.BR acl_free (3),
.BR acl (5)
