.\" Access Control Lists manual pages
.\"
.\" (C) 2002 Andreas Gruenbacher, <a.gruenbacher@computer.org>
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.TH ACL_EQUIV_MODE 3 "Linux ACL Library" "March 2002" "Access Control Lists"
.SH NAME
acl_equiv_mode \- check for an equivalent ACL
.SH LIBRARY
Linux Access Control Lists library (libacl, \-lacl).
.SH C SYNOPSIS
.sp
.nf
.B #include <sys/types.h>
.B #include <sys/acl.h>
.sp
.B "int acl_equiv_mode (acl_t \f2acl\f3, mode_t *\f2mode_p\f3);"
.Op
.SH DESCRIPTION
The
.B acl_equiv_mode
function checks if the ACL pointed to by the argument
.I acl
contains only the required ACL entries of tag types
ACL_USER_OBJ, ACL_GROUP_OBJ, and ACL_OTHER, and contains no
permissions other that ACL_READ, ACL_WRITE or ACL_EXECUTE.
If the ACL has this form, it can can be fully represented with
the traditional file permission bits, and is considered
equivalent with the traditional file permission bits.
.PP
If
.I acl
is an equivalent ACL and the pointer
.I mode_p
is not NULL, the value pointed to by
.I mode_p
is set to the value that defines the same owner, group and other
permissions as contained in
the ACL.
.SH RETURN VALUE
Upon successful completion, this function returns the value 0 if
.I acl
is an equivalent ACL, and the value 1 if
.I acl
is not an equivalent ACL. Otherwise, the value -1 is returned, and
.B errno
is set to indicate the error.
.SH ERRORS
If any of the following conditions occur, the
.B acl_equiv_mode
function returns the value -1 and sets
.B errno
to the corresponding value:
.TP
.SM
\%[EINVAL]
The argument
.I acl
is not a valid pointer to an ACL.
.SH STANDARDS
This is a non-portable, Linux specific extension to the ACL manipulation
functions defined in IEEE Std 1003.1e draft 17 (\(lqPOSIX.1e\(rq, abandoned).
.SH AUTHOR
Written by
.I "Andreas Gruenbacher"
<a.gruenbacher@computer.org>.
.SH SEE ALSO
.BR acl_from_mode (3),
.BR acl (5)
