.TH ACL_SET_COMPAT 3
.SH NAME
acl_set_compat \- set compatibility mode for ACL library
.SH SYNOPSIS
.B #include <sys/acl.h>
.PP
.B void acl_set_compat(acl_compat_t compat_bits);
.SH DESCRIPTION
.I acl_set_compat
sets the compatibility mode for various IRIX and Linux ACL functionality.
The ACL semantics for IRIX even though they are based on the Posix 1003.1e 
withdrawn ACL standard, are subtly different from the semantics of
ext2 ACLs and BSD ACLs. The default semantics used are that of the ext2
Posix ACLs and a call to this function should only be made to gain
IRIX compatibility.
.PP
\f2Compat_bits\f1 is a bit-vector formed by or'ing compatiblity macros
with the prefix of \f2ACL_COMPAT_\f1. Each call to this function will
add to the current compatibility vector. Given a \f2compat_bits\f1 value
of zero will reset it.
If \f2compat_bits\f1 is set to \f2ACL_COMPAT_IRIXGET\f1 then the semantics for 
.BR acl_get_fd (8)
and
.BR acl_get_file (8)
are changed in the cases where no ACL was ever explicitly set for
a file or directory.
Please refer to
.BR acl_get_fd (8)
and
.BR acl_get_file (8)
for a description of the differing semantics.
.SH SEE ALSO
.BR acl_get_fd (8),
.BR acl_get_file (8).
