.\" Access Control Lists manual pages
.\"
.\" (C) 2002 Andreas Gruenbacher, <a.gruenbacher@computer.org>
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.TH ACL_EXTENDED_FD 3 "Linux ACL Library" "March 2002" "Access Control Lists"
.SH NAME
acl_extended_fd \- test for information in the ACL by file descriptor
.SH LIBRARY
Linux Access Control Lists library (libacl, \-lacl).
.SH C SYNOPSIS
.sp
.nf
.B #include <sys/types.h>
.B #include <sys/acl.h>
.sp
.B "int acl_extended_fd (int \f2fd\f3);"
.Op
.SH DESCRIPTION
The
.B acl_extended_fd
function returns 1 if the file referred to by the argument
.I path_p
is associated with an extended access ACL. The function returns 0
if the file does not have an extended access ACL.
.PP
An extended ACL is an ACL that contains entries other than the three
required entries of tag types ACL_USER_OBJ, ACL_GROUP_OBJ and ACL_OTHER.
If the result of the
.B acl_extended_fd
function for a file object is 0,
then the ACL defines no discretionary access rights other than those
already defined by the traditional file permission bits.
.PP
Access to the file object may be further restricted by other
mechanisms, such as Mandatory Access Control schemes. The
.BR access (2)
system call can be used to check whether a given type of access to a file
object would be granted.
.SH RETURN VALUE
If successful, the
.B acl_extended_fd
function returns 1 if the file object referred to by
.I fd
has an extended access ACL, and 0 if the file object referred to by
.I fd
does not have an extended access ACL. Otherwise, the value -1
is returned and the global variable
.B errno
is set to indicate the error.
.SH ERRORS
If any of the following conditions occur, the
.B acl_extended_fd
function returns -1 and sets
.B errno
to the corresponding value:
.TP
.SM
\%[ENOTSUP]
The file system on which the file identified by
.I fd
is located does not support ACLs, or ACLs are disabled.
.SH STANDARDS
This is a non-portable, Linux specific extension to the ACL manipulation
functions defined in IEEE Std 1003.1e draft 17 (\(lqPOSIX.1e\(rq, abandoned).
.SH AUTHOR
Written by
.I "Andreas Gruenbacher"
<a.gruenbacher@computer.org>.
.SH SEE ALSO
.BR access (2),
.BR acl (5)
